#!/bin/sh
DEFAULT_OPTION="-O encoding=utf-8 -O style=monokai -f console256"
case "$1" in
    *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
        pygmentize $DEFAULT_OPTION -g "$1";;
    Gemfile|Vagrantfile|Capfile)
        pygmentize $DEFAULT_OPTION -l ruby "$1"
        ;;
    *.xml.dist|*.xml.sample)
        pygmentize $DEFAULT_OPTION -l xml "$1"
        ;;
    *.php.dist|*.php.sample)
        pygmentize $DEFAULT_OPTION -l php "$1"
        ;;
    .zshrc)
        pygmentize -f 256 -l sh "$1"
        ;;
    *)
        grep "#\!/bin/zsh" "$1" > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize -f 256 -l sh "$1"
        else
            echo "Unsupported filetype lexer from Pygments"
            echo "See: http://pygments.org/docs/lexers/"
            exit 1
        fi
esac

exit 0
